### ISSUE TITLE
kubectl --help

### ISSUE THREAD

**Issue by chicuongha** [zimfw/k#2]
Hello,

Is it possible to have kubectl --help or anything shorter for k --help.?
It works with k g --help, but not for k --help.

Thanks.

**Comment by ericbn** [comment]
There are at least two things we can do here:
1. Add an `h` option key, so `k gh` is the same as `kubectl get --help` .
2. Allow 0 command keys, so `k h` is the same as `kubectl --help`. If no command key is given, I think no resource key should be allowed, so `k po` is invalid.

An alternative to 2 is:
2. Add an `h` command, so `k h` is the same as `kubectl help`.

What do you think?
