### ISSUE TITLE
`command not found: _kubectl` when using autocomplete

### ISSUE THREAD

**Issue by bisasuperstar** [zimfw/k#3]
- [x] I've checked the [existing issues](../issues?q=is%3Aissue) and I'm not duplicating a report.
- [x] I'm using the [latest version](https://github.com/zimfw/zimfw/releases/latest) of `zimfw`.
- [x] I've checked the [Changelog](https://github.com/zimfw/zimfw/blob/master/CHANGELOG.md) and I'm not being affected by documented changes.
- [x] I've checked the [📢 Announcements](https://github.com/zimfw/zimfw/discussions/426?sort=new) and I'm not being affected by announced changes.
- [x] I was able to reproduce the issue with a clean installation of Zim.
- [x] I've pasted the output of `zimfw info` below.

**Describe the bug**  
When I press TAB for autocomplete I get `command not found: _kubectl | _k:6: command not found: _kubectl`

**Steps to reproduce**  
I have the completion module sourced after the `k` module. 

Whenever I try to press tab for autosuggestions I get the error above.

**zimfw info**  
```
# In a terminal, run zimfw info, and paste the output here.
zimfw version:        1.11.3 (built at 2023-02-26 00:43:41 UTC, previous commit is 6a24459)
OSTYPE:               darwin22.1.0
TERM:                 xterm-256color
TERM_PROGRAM:         iTerm.app
TERM_PROGRAM_VERSION: 3.4.19
ZIM_HOME:             /Users/albi/.zim
ZSH_VERSION:          5.9
```

**Comment by casret** [comment]
I am also seeing this on a fresh install:
```zimfw version:        1.12.1 (built at 2023-09-16 18:25:16 UTC, previous commit is 26151d2)
LANG:                 C.UTF-8
OSTYPE:               linux-gnu
TERM:                 xterm-256color
TERM_PROGRAM:         WezTerm
TERM_PROGRAM_VERSION: 20230712-072601-f4abf8fd
ZIM_HOME:             /home/casret/.zim
ZSH_VERSION:          5.8.1```

**Comment by bisasuperstar** [comment]
@casret - do you have the [kubectl autocomplete](https://kubernetes.io/docs/reference/kubectl/cheatsheet/) installed by any chance?

**Comment by casret** [comment]
So what I did to work around this is to add the `source <(command kubectl completions zsh>`  myself.  I find it strange that it's commented out in the init.zsh.
